// Compiled by ClojureScript 1.7.228 {}
goog.provide('intolambda.footer');
goog.require('cljs.core');
goog.require('cljsjs.material');
goog.require('intolambda.utils');
intolambda.footer.footer_component = (function intolambda$footer$footer_component(roles,contributors){
return new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"section","section",-300141526),new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"id","id",-1388402092),"footer"], null),new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"div.content-grid.mdl-grid.dark-primary-color.text-primary-color","div.content-grid.mdl-grid.dark-primary-color.text-primary-color",508730626),new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"div.mdl-cell.md-cell--4-col.md-cell--2-col-tablet.md-cell--2-col-phone","div.mdl-cell.md-cell--4-col.md-cell--2-col-tablet.md-cell--2-col-phone",-333235976),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"h5.mdl-color-text--accent","h5.mdl-color-text--accent",-951100547),intolambda.utils.icon_text_line.call(null,"info_outline","about")], null),intolambda.utils.icon_text_line.call(null,"event","to be announced","with-ear-muffs"),intolambda.utils.icon_text_line.call(null,"place","to be announced","with-ear-muffs")], null),new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"div.mdl-cell.md-cell--4-col.md-cell--2-col-tablet.md-cell--2-col-phone","div.mdl-cell.md-cell--4-col.md-cell--2-col-tablet.md-cell--2-col-phone",-333235976),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"h5.mdl-color-text--accent","h5.mdl-color-text--accent",-951100547),intolambda.utils.icon_text_line.call(null,"power","contact")], null),intolambda.utils.icon_text_line.call(null,"home","www.icslab.eu"),intolambda.utils.icon_text_line.call(null,"mail","icslabcrew@gmail.com")], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"div.mdl-cell.md-cell--4-col.md-cell--2-col-tablet.md-cell--2-col-phone","div.mdl-cell.md-cell--4-col.md-cell--2-col-tablet.md-cell--2-col-phone",-333235976),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"h5.mdl-color-text--accent","h5.mdl-color-text--accent",-951100547),intolambda.utils.icon_text_line.call(null,"person_add","contribute")], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"p","p",151049309),"Would you like to contribute as volunteer, expert, sponsor or partner?",new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"button.mdl-color-text--accent.dark-primary-color.link-like","button.mdl-color-text--accent.dark-primary-color.link-like",1372092128),new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"on-click","on-click",1632826543),(function (){
intolambda.utils.show_element.call(null,"contributors");

return document.location = "#contributors";
})], null),"Let's get in touch"], null)], null)], null)], null)], null);
});

//# sourceMappingURL=footer.js.map