// Compiled by ClojureScript 1.7.228 {:static-fns true, :optimize-constants true}
goog.provide('intolambda.footer');
goog.require('cljs.core');
goog.require('intolambda.utils');
intolambda.footer.footer_component = (function intolambda$footer$footer_component(roles,contributors){
return new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$section,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.cst$kw$id,"footer"], null),new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$div$content_DASH_grid$mdl_DASH_grid$dark_DASH_primary_DASH_color$text_DASH_primary_DASH_color,new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$div$mdl_DASH_cell$md_DASH_cell_DASH__DASH_4_DASH_col$md_DASH_cell_DASH__DASH_2_DASH_col_DASH_tablet$md_DASH_cell_DASH__DASH_2_DASH_col_DASH_phone,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$h5$mdl_DASH_color_DASH_text_DASH__DASH_accent,intolambda.utils.icon_text_line.cljs$core$IFn$_invoke$arity$2("info_outline","about")], null),intolambda.utils.icon_text_line.cljs$core$IFn$_invoke$arity$3("event","to be announced","with-ear-muffs"),intolambda.utils.icon_text_line.cljs$core$IFn$_invoke$arity$3("place","to be announced","with-ear-muffs")], null),new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$div$mdl_DASH_cell$md_DASH_cell_DASH__DASH_4_DASH_col$md_DASH_cell_DASH__DASH_2_DASH_col_DASH_tablet$md_DASH_cell_DASH__DASH_2_DASH_col_DASH_phone,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$h5$mdl_DASH_color_DASH_text_DASH__DASH_accent,intolambda.utils.icon_text_line.cljs$core$IFn$_invoke$arity$2("power","contact")], null),intolambda.utils.icon_text_line.cljs$core$IFn$_invoke$arity$2("home","www.icslab.eu"),intolambda.utils.icon_text_line.cljs$core$IFn$_invoke$arity$2("mail","icslabcrew@gmail.com")], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$div$mdl_DASH_cell$md_DASH_cell_DASH__DASH_4_DASH_col$md_DASH_cell_DASH__DASH_2_DASH_col_DASH_tablet$md_DASH_cell_DASH__DASH_2_DASH_col_DASH_phone,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$h5$mdl_DASH_color_DASH_text_DASH__DASH_accent,intolambda.utils.icon_text_line.cljs$core$IFn$_invoke$arity$2("person_add","contribute")], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$p,"Would you like to contribute as volunteer, expert, sponsor or partner?",new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$button$mdl_DASH_color_DASH_text_DASH__DASH_accent$dark_DASH_primary_DASH_color$link_DASH_like,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.cst$kw$on_DASH_click,(function (){
intolambda.utils.show_element.cljs$core$IFn$_invoke$arity$1("contributors");

return document.location = "#contributors";
})], null),"Let's get in touch"], null)], null)], null)], null)], null);
});
